# Netlify configuration file

[build]
  command = "npm run build" # Your build command
  publish = "dist"          # Your publish directory

[functions]
  directory = "netlify/functions" # Standard directory for Netlify functions
  # Removed incorrect timeout line - will use Netlify default
  # Optional: Specify node version for functions if needed
  # node_bundler = "esbuild"
  # node_version = "18"